In [2]:
import numpy as np

i = np.array([1, 2, 3, 4, 5])
j = i.copy()

i[0] = 10
i[1] = 20

print(i)
print(j)

[10 20  3  4  5]
[1 2 3 4 5]


In [4]:
i = np.array([1, 2, 3, 4, 5])

j = i.view() 

i[0] = 10
i[1] = 20

print(i)
print(j)

[10 20  3  4  5]
[10 20  3  4  5]


In [6]:
 i = np.array([1, 2, 3, 4, 5])

 j = i.view() # j = view data

j[0] = 10
j[1] = 20

print(i)
print(j)

print()

print(i.base)
print(j.base)

[10 20  3  4  5]
[10 20  3  4  5]

None
[10 20  3  4  5]
